version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    links:
      - api
  api:
    build: ./api
    command: bundle exec rails s -b 0.0.0.0
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=thisisaverygoodsecret
      - PORT=5000
    links:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  bundle:
  pg_data:


