#!/bin/bash
#
# builds latest from code and runs application

set -e

# ensure we're at project root
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" && pwd  )"
cd "$DIR/.."

# Because client isn't "running" in production, make build first
# before shutting down other services.
docker-compose -f production.yml build client
docker-compose -f production.yml run --rm client yarn build

docker-compose stop
docker-compose -f production.yml build api
docker-compose -f production.yml run --rm api bin/setup

docker-compose -f production.yml build nginx
docker-compose -f production.yml up -d nginx

echo "allowing 10 seconds to boot before checking health"
for i in {1..10}; do
  echo -n '.'
  sleep 1
done

echo
curl --silent --show-error --max-time 30 --fail "127.0.0.1"
sleep 1
echo
curl --silent --show-error --max-time 30 --fail "127.0.0.1/api/health" | jq
