#!/bin/bash
set -eu

DEPLOYED_DIR='/home/deploy/current'
GIT_SERVER_DIR='/home/deploy/farmenvy/dotcom.git'

echo '=== Activating Firewall (only SSH allowed) ==='
ufw --force reset
ufw allow ssh
ufw --force enable
ufw status

echo '=== Installing Kernel with LXC and AUFS Support ==='
export DEBIAN_FRONTEND=noninteractive
apt-get -qq update
apt-get install -qqy linux-image-extra-`uname -r` git curl jq

echo '=== Verifying Docker Installation ==='
docker run busybox /bin/echo '*** It works! ***'

echo '=== Creating deploy user ==='
adduser --disabled-password --gecos "" deploy
usermod -aG docker deploy

su -- deploy <<EOF
  echo '=== Initializing farmenvy/dotcom git repo ==='
  mkdir -p "$GIT_SERVER_DIR"
  git init --bare "$GIT_SERVER_DIR"

  echo '=== Installing and Symlinking post-receive hook ==='
  git clone --depth 1 https://github.com/farmenvy/dotcom.git "$DEPLOYED_DIR"
  ln -s "$DEPLOYED_DIR/config/server/hooks/post-receive" "$GIT_SERVER_DIR/hooks/post-receive"

  echo '=== Adding authorized keys ==='
  mkdir -p /home/deploy/.ssh
  ln -s "$DEPLOYED_DIR/config/server/authorized_keys" /home/deploy/.ssh/authorized_keys
EOF

echo '*** DONE ***'

