#!/bin/bash
#
# Usage:
#
# script/destroy-server DROPLETNAME
#

DROPLET_NAME="$1"

doctl() {
  docker run -e DIGITALOCEAN_ACCESS_TOKEN="$DIGITALOCEAN_ACCESS_TOKEN" farmenvy/doctl compute "$@"
}

lookup_droplet_id() {
  doctl droplet list | \
    grep "\s$DROPLET_NAME\s" | \
    awk '{ print $ 1 }'
}

destroy_server() {
  local id=$(lookup_droplet_id)

  if [ -n "$id" ]
  then
    echo "destroying $DROPLET_NAME..."
    doctl droplet delete -f "$id" && echo 'OK'
  else
    echo "!! couldn't find droplet named $DROPLET_NAME"
    exit 1
  fi
}

remove_address_file() {
  local DESTINATION="config/server/addresses/$DROPLET_NAME"

  if [ -z "$DROPLET_NAME" ]
  then
    echo 'no droplet name specified!'
    exit 1
  elif [ ! -f "$DESTINATION" ]
  then
    echo "file does not exist: $DESTINATION"
    exit 1
  else
    echo "removing: $DESTINATION"
    rm -f "$DESTINATION"
  fi

  echo "OK"
}

destroy_server
remove_address_file
