#!/bin/bash

IP_ADDRESS=${1:-unspecified}

echo "allowing 10 seconds to boot before checking health"
for i in {1..10}; do
  echo -n '.'
  sleep 1
done

echo
echo '==> checking front page'
curl --silent --show-error --max-time 30 --fail "$IP_ADDRESS"

sleep 1

echo
echo '==> checking /api/health'
curl --silent --show-error --max-time 30 --fail "$IP_ADDRESS/api/health"
echo
