#!/bin/bash

IP_ADDRESS=${1:-unspecified}

echo "allowing 10 seconds to boot before checking health"
for i in {1..10}; do
  echo -n '.'
  sleep 1
done

echo
echo '==> checking front page'
curl --silent --show-error --max-time 5 --fail "$IP_ADDRESS"
res="$?"
if test "$res" != "0"; then exit 1; fi
echo

echo '==> checking /api/health'
curl --silent --show-error --max-time 5 --fail "$IP_ADDRESS/api/health"
res="$?"
if test "$res" != "0"; then exit 1; fi
echo
