#!/bin/bash

set -e

# ensure we're at project root
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" && pwd  )"
cd "$DIR/.."

FLOATING_IP=$(cat ./config/server/addresses/float)
GIT_SHORT_REF=$(echo "$GIT_COMMIT" | cut -c1-7)
STAGING_IP="$(cat $STAGING_IP_PATH)"
DROPLET_ID=$(doctl droplet list | grep "$STAGING_IP" | awk '{ print $1 }')
CURRENT_STAGING=$(cat ./STAGING)

doctl() {
  docker run -e DIGITALOCEAN_ACCESS_TOKEN="$DIGITALOCEAN_ACCESS_TOKEN" farmenvy/doctl compute "$@"
}

echo "---> creating tag $GIT_SHORT_REF"
git tag "$GIT_SHORT_REF"

echo "---> pushing tag $GIT_SHORT_REF"
git push origin "$GIT_SHORT_REF"

if [ "$CURRENT_STAGING" == green ]; then
  NEW_PRODUCTION=green
elif [ "$CURRENT_STAGING" == blue ]; then
  NEW_PRODUCTION=blue
else
  echo "'$CURRENT_STAGING' is invalid.  It should be green or blue."
  exit 1
fi

STAGING_IP_PATH="./config/server/addresses/$NEW_PRODUCTION"

unassign_floating_ip() {
  doctl floating-ip-action unassign "$FLOATING_IP"
}

assign_floating_ip() {
  doctl floating-ip-action assign "$FLOATING_IP" "$DROPLET_ID"
  echo "---> assigned floating ip: $FLOATING_IP to: $STAGING_IP ($NEW_PRODUCTION)"
}

echo "---> unassigning floating ip: $FLOATING_IP"
unassign_floating_ip || true

echo "---> reassigning floating ip to: $NEW_PRODUCTION"
assign_floating_ip

