#!/bin/bash
#
# Needs these variables available in environment:
#
# CONSOLE_URL=http://google.com
# RUN_STATUS=failure
# BUILD_NUMBER=123
# STAGING_IP=127.0.0.1
# GIT_COMMIT=64fd74c172a6697bb72afb8917e8c881a7e10589

GIT_COMMIT_MSG=$(git log -1 --pretty=%B)
GITHUB_COMMIT_URL="github.com/farmenvy/dotcom/commit/$GIT_COMMIT"
GIT_SLACK_LINK="<http://$GIHUB_COMMIT_URL|$GITHUB_COMMIT_MSG>"
STAGING_LINK="<http://$STAGING_IP|$STAGING>"
STAGING=$(cat ./STAGING)

RUN_STATUS=${1:-$RUN_STATUS}

if [ "$RUN_STATUS" == success ]
then
  if [ "$STAGING" == green ]
  then
    COLOR=good
  else
    COLOR='#006dfc'
  fi

  SLACK_TEXT="Deployed $GIT_SLACK_LINK to $STAGING_LINK"
else
  COLOR=danger
  SLACK_TEXT="$GIT_SLACK_LINK failed :fire:"
fi


PAYLOAD=$(cat <<EOF
{
  "attachments": [
    {
      "fallback": "$RUN_STATUS",
      "color": "$COLOR",
      "title": "Build: $BUILD_NUMBER",
      "title_link": "$CONSOLE_URL",
      "text": "$SLACK_TEXT"
    }
  ]
}
EOF
)

curl -X POST \
  -H 'Content-type: application/json' \
  --silent --data "$PAYLOAD" \
  "$SLACK_WEBHOOK_URL"
