#!/bin/bash
#
# Needs these variables available in environment:
#
# CONSOLE_URL=http://google.com
# RUN_STATUS=failure
# BUILD_NUMBER=123
# STAGING_IP=127.0.0.1
# GIT_COMMIT=64fd74c172a6697bb72afb8917e8c881a7e10589

GIT_SHORT_REF=$(echo "$GIT_COMMIT" | cut -c1-7)
GITHUB_COMMIT_URL="github.com/farmenvy/dotcom/commit/$GIT_COMMIT"
STAGING=$(cat ./STAGING)

RUN_STATUS=${1:-$RUN_STATUS}

if [ "$RUN_STATUS" == success ]
then
  COLOR=good
  SLACK_TEXT="Deployed <https://$GIHUB_COMMIT_URL|$GIT_SHORT_REF> to <http://$STAGING_IP|$STAGING>"
else
  COLOR=danger
  SLACK_TEXT="<$GIHUB_COMMIT_URL|$GIT_SHORT_REF> failed :fire:"
fi


PAYLOAD=$(cat <<EOF
{
  "attachments": [
    {
      "fallback": "$RUN_STATUS",
      "color": "$COLOR",
      "title": "Build: $BUILD_NUMBER",
      "title_link": "$CONSOLE_URL",
      "text": "$SLACK_TEXT"
    }
  ]
}
EOF
)

curl -X POST \
  -H 'Content-type: application/json' \
  --silent --data "$PAYLOAD" \
  "$SLACK_WEBHOOK_URL"
