#!/bin/bash
#
# Swaps staging and production environments.

set -eu

# ensure we're at lb root
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" && pwd  )"
cd "$DIR/../lb"

nginx_conf_template='./nginx.template.conf'
template_backup="$nginx_conf_template.bak"
staging=$(cat ../STAGING)

# Make a backup first thing.
cp "$nginx_conf_template" "$template_backup"

if [ "$staging" == blue ]; then
  new_production=green
elif [ "$staging" == green ]; then
  new_production=blue
else
  echo "staging is invalid: '$staging'"
  exit 1
fi

sed -i "s/<STAGING>/$staging/g" "$nginx_conf_template"
sed -i "s/<PRODUCTION>/$new_production/g" "$nginx_conf_template"

mv "$nginx_conf_template" nginx.conf
cp "$template_backup" "$nginx_conf_template"

echo "STAGING file value: $staging"
cat nginx.conf | grep proxy_pass
