#!/bin/bash

set -eu

# ensure we're at project root
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" && pwd  )"
cd "$DIR/.."

LB_IP=$(cat ./config/server/addresses/lb)
NGINX_CONFIG='./lb/nginx.conf'

if [ ! -f "$NGINX_CONFIG" ]; then
  echo "$NGINX_CONFIG not found!"
  exit 1
fi

echo "+ adding $LB_IP as known host"
ssh-keygen -R "$LB_IP"
ssh-keyscan "$LB_IP" >> ~/.ssh/known_hosts

echo '+ scp latest nginx.conf to loadbalancer'
scp "$NGINX_CONFIG" "deploy@$LB_IP:/home/deploy/current/lb/nginx.conf"

echo '+ reloading NGINX'
ssh "deploy@$LB_IP" 'docker kill -s HUP nginx'
