AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/spec_helper
    - db/**/*

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - config/**/*
    - Guardfile

Metrics/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false
