FROM phusion/passenger-ruby24

# set environment variables
ENV APP_NAME farmenvyapi
ENV HOME /root
ENV WEBAPP /home/app/webapp

RUN mkdir -p ${WEBAPP}

# use baseimage-docker’s init process
# bundling is done in boot.sh
CMD ["/sbin/my_init"]

# add boot script
RUN mkdir -p /etc/my_init.d
ADD boot.sh /etc/my_init.d/boot.sh
RUN chmod +x /etc/my_init.d/boot.sh

# Run Bundle in a cache efficient way
WORKDIR /tmp
RUN gem install bundler --no-ri --no-rdoc
ADD Gemfile /tmp/Gemfile
ADD Gemfile.lock /tmp/Gemfile.lock
RUN su app -- bundle install -j 7 --without development test

# setup client dependencies
# RUN mkdir -p ${WEBAPP}/client
# WORKDIR ${WEBAPP}/client
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash
RUN apt-get install -y nodejs
RUN npm install -g yarn
# COPY client/package.json ${WEBAPP}/client/
# COPY client/yarn.lock ${WEBAPP}/client/
# RUN yarn --pure-lockfile

# start Nginx / Passenger
RUN rm -f /etc/service/nginx/down

# remove the default site
RUN rm /etc/nginx/sites-enabled/default

# add nginx.conf
ADD nginx.conf /etc/nginx/sites-enabled/${APP_NAME}.conf

# preserve environment variables
ADD nginx_env.conf /etc/nginx/main.d/env.conf

# Add the rails app
ADD . ${WEBAPP}
# WORKDIR ${WEBAPP}/client
# RUN yarn build
# RUN mv build ${WEBAPP}/public
RUN chown -R app:app ${WEBAPP}

WORKDIR ${WEBAPP}
EXPOSE 80

# clean up when done
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
